import axios from 'axios';
import { log } from 'console';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css';
import Navbar from '../components/Navbar';
import Podium from '../components/Podium';
import News from '../components/News';
const website_uri = 'https://osunorway.vercel.app/';

export default function Home(data: any) {
	useEffect(() => {
		const getSessionToken = async () => {
			const response = await fetch(
				'http://localhost:3000/api/GetSessionToken'
			);
			const data = await response.json();
			document.cookie = `bearer=${
				data.sessionToken
			}; SameSite=none; expires=${Date.now() + 18000}`;
		};
		getSessionToken();
	}, []);

	/*OLD
  useEffect(() => {
    const getBearerToken = async () => {
      try {
        let response = await fetch(website_uri + "api/requestData", {
          method: "POST",
          body: JSON.stringify({ authCode: authCode }),
        });

        let data = await response.json();
        console.log(data);

        setAccessToken(data["access_token"]);
        data["access_token"] &&
          localStorage.setItem("accessToken", data["access_token"]);
        console.log(data["access_token"]);
      } catch (err) {
        console.error(err);
      }
    };

    getBearerToken();
    const token = localStorage.getItem("accessToken");
  }, [authCode]);
  */
	/*

Get the auth token through the params
save auth token in cookies or storage
Reset website by pushing a new route (going back to default route)
use token to get api endpoint response
display response data


  const router = useRouter();

  useEffect(() => {
    const setAuth = async () => {
      setAuthCode(String(router.query.code));
      console.log(authCode);
    };
    setAuth();
  }, [router.query, authCode]);
*/

	/*TODO
make a global store (redux, react storage etc...) 
^ session storage




get bearer token on page load 
place token in storage and use it for page\
*/

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<header>
				<Navbar></Navbar>
			</header>
			<main className='bg-osu_background_dark w-screen min-h-screen m-0 flex flex-col '>
				<Podium
					one={data.data.ranking[0].user}
					two={data.data.ranking[1].user}
					three={data.data.ranking[2].user}></Podium>
				<News></News>
			</main>

			<footer className={styles.footer}></footer>
		</div>
	);
}

export async function getServerSideProps({ req, res }: any) {
	const url = new URL('https://osu.ppy.sh/api/v2/rankings/mania/performance');

	let params: any = {
		country: 'NO',
		filter: 'all',
	};
	Object.keys(params).forEach((key) =>
		url.searchParams.append(key, params[key])
	);

	const PUBLIC_BEARER = req.cookies.bearer;
	const options = {
		method: 'GET',
		headers: {
			Authorization: `Bearer ${PUBLIC_BEARER}`,
			'Content-Type': 'application/json',
		},
	};

	const leaderData = await fetch(url, options);
	const data = await leaderData.json();
	return {
		props: {
			data,
		},
	};
}
