import axios from "axios";
import { log } from "console";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";

const website_uri = "https://osunorway.vercel.app/";

export default function Home(JSON_DATA: any) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar></Navbar>
      </header>
      <main className="bg-osu_background_dark w-screen h-auto p-0 m-0">
        <div className=" w-screen h-auto flex flex-col gap-6 p-6 items-center ">
          <div className="  bg-osu_background_card h-36 w-[70%] rounded-md gap-6 flex items-center justify-start px-6">
            <div className="w-32 h-[40%] bg-osu_background_info rounded flex items-center justify-center text-osu_text_white">
              Global rank
            </div>
            <div className="w-32 h-[40%] bg-osu_background_info rounded flex items-center justify-center text-osu_text_white">
              Global rank
            </div>
            <div className="w-32 h-[40%] bg-osu_background_info rounded flex items-center justify-center text-osu_text_white">
              Global rank
            </div>
          </div>
          {JSON_DATA["JSON_DATA"].ranking.map((player: any, index: number) => {
            return (
              <a
                className=" hover:scale-110 duration-300 hover:cursor-pointer rounded shadow-md text-osu_text_white shadow-osu_background_card w-[70%] h-24 flex gap-12 items-center justify-start bg-osu_background_card "
                key={player.global_rank}
                href={"/user/" + player.user.id}
              >
                <img
                  src={player.user.avatar_url}
                  className=" h-full aspect-square bg-center rounded-l"
                ></img>
                <h2>{player.user.username}</h2>
                <p>global rank: {player.global_rank}</p>
                <p>ranking in norway: {index + 1}</p>
              </a>
            );
          })}
          ;
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getServerSideProps() {
  const url = new URL("https://osu.ppy.sh/api/v2/rankings/mania/performance");

  let params: any = {
    country: "NO",
    filter: "all",
    variant: "4k",
  };
  Object.keys(params).forEach((key) =>
    url.searchParams.append(key, params[key])
  );

  const PUBLIC_BEARER =
    "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxOTI3MSIsImp0aSI6IjJlNjQ1YjU1N2ZhMmQ0NzZiMDQ0MmZiMGExMzdmNTRiZGYzNzc3NWQ5YWUwNGFhNWU2NmVmMGY1ZTg3MDJkZDkwM2U1NWZkM2E2MzBjN2U2IiwiaWF0IjoxNjcyMTU4ODc4LjAwNTA0NiwibmJmIjoxNjcyMTU4ODc4LjAwNTA0OSwiZXhwIjoxNjcyMjQ0NzgyLjYyNDc2Niwic3ViIjoiIiwic2NvcGVzIjpbInB1YmxpYyJdfQ.ee4i6OpIr-tT4XHIsq33h-mWG-G0okskFB8dj3zF3hTTOsHrFiji7f-lpqWzCoBOvT0UGpb_GzAivfT87zsdHRFDk87PFSCalm8nIXfl33C6LbFca70FYinXtoqw1zslSYW3NkG0N4hkzb2zdbTY4J3dQs99ArdGLk_zZs5jnffOHWZubPwy-aaT3mxcQWGkHI146uJX8Uw9ZEbspTe8C4Gkr1M94a6nm0vhJFzQA0lQa7iFWYjxtevgJV6brMTgV7d1O9tkl0SqETb9Bq3gb87cCWOICRAeClD-QHs0EI-Qb8mHmKisW6r3AJ1QC0V9YhxiVN1PD_4BP1K8Hj-jw1T17u97JPafKRKVwep6Om4XZ0BQn0HXaIS3ERArVkvf4gkVFxkrsQWW7EppXzZzIKJTbSVGmtvvJUioXIQbjodfLm7BpXQh-yJQi0Q86PFXBMxSDQt-ERMxy-bJdQEuki2gSkT_K_XfLVYO3-tOxhRyEl2IIwYkmYiyLJWWHQ8uUkhCN_xN2__a2nQA-Ye6rGwyy_zkO0DmDWT3lQLrRJxKKldZu8ek2RmzXjNhDQH58WOZol7lCtc7M6FGDrum2AlHWzD5Eqx5LiW5Au5w9THnzpujEMmTQy1kDO0uvRCXpf4xBV_MlnTlhLTUfc60Gv1cBKLGKNYwX6eyNfLh_jc";

  const options = {
    method: "GET",
    headers: {
      Authorization: `Bearer ${PUBLIC_BEARER}`,
      "Content-Type": "application/json",
    },
  };

  const leaderData = await fetch(url, options);
  const JSON_DATA = await leaderData.json();
  return {
    props: {
      JSON_DATA,
    },
  };
}
